
version: '3.1'

services:

  web-server:
    image: php:7.2-apache
    restart: always
    container_name: Kuhni    
    ports:
      - 8070:80
    volumes:
      - ./html/:/var/www/html
    networks:
      - project

networks:
  project:
    driver: bridge

